//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Website.App_LocalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Error {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Error() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Website.App_LocalResources.Error", typeof(Error).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please check your email to active your account..
        /// </summary>
        public static string ActiveAccount {
            get {
                return ResourceManager.GetString("ActiveAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email is already registered..
        /// </summary>
        public static string DuplicatedEmail {
            get {
                return ResourceManager.GetString("DuplicatedEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keyword is already registered..
        /// </summary>
        public static string DuplicatedKeyword {
            get {
                return ResourceManager.GetString("DuplicatedKeyword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile phone number is already registered..
        /// </summary>
        public static string DuplicatedPhone {
            get {
                return ResourceManager.GetString("DuplicatedPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The URL is registered..
        /// </summary>
        public static string DuplicatedURL {
            get {
                return ResourceManager.GetString("DuplicatedURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your account is inuse to access the system with another device. Please log off first..
        /// </summary>
        public static string InuseAccount {
            get {
                return ResourceManager.GetString("InuseAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please delete the categories relative to the campaign first..
        /// </summary>
        public static string InuseCampaign {
            get {
                return ResourceManager.GetString("InuseCampaign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please delete the URLs relative to the category first..
        /// </summary>
        public static string InuseCategory {
            get {
                return ResourceManager.GetString("InuseCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please delete the details relative to the Keyword first..
        /// </summary>
        public static string InuseKeyword {
            get {
                return ResourceManager.GetString("InuseKeyword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We cannot detect your mobile phone number or password is incorrect..
        /// </summary>
        public static string InvalidAccount {
            get {
                return ResourceManager.GetString("InvalidAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email is invalid..
        /// </summary>
        public static string InvalidEmailFormat {
            get {
                return ResourceManager.GetString("InvalidEmailFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must has at least 8 characters with 1 uppercase letter and 1 number..
        /// </summary>
        public static string InvalidPassword {
            get {
                return ResourceManager.GetString("InvalidPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your account was locked. Please contact the administrator..
        /// </summary>
        public static string LockedAccount {
            get {
                return ResourceManager.GetString("LockedAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The confirmed email is not equal to the email!.
        /// </summary>
        public static string NotEqualConfirmedEmail {
            get {
                return ResourceManager.GetString("NotEqualConfirmedEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please check that your passwords match and try again..
        /// </summary>
        public static string NotEqualConfirmedPassword {
            get {
                return ResourceManager.GetString("NotEqualConfirmedPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We cannot detect your mobile phone number..
        /// </summary>
        public static string NotExistPhone {
            get {
                return ResourceManager.GetString("NotExistPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email system is off. Please contact the administrator..
        /// </summary>
        public static string OffEmailSystem {
            get {
                return ResourceManager.GetString("OffEmailSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile phone number must be numeric..
        /// </summary>
        public static string OnlyInteger {
            get {
                return ResourceManager.GetString("OnlyInteger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to at least 8 characters with 1 uppercase letter and 1 number.
        /// </summary>
        public static string PasswordRule {
            get {
                return ResourceManager.GetString("PasswordRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error! Please contact the administrator..
        /// </summary>
        public static string PerformmingError {
            get {
                return ResourceManager.GetString("PerformmingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please check your email to renew your password..
        /// </summary>
        public static string RenewPassword {
            get {
                return ResourceManager.GetString("RenewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing email address..
        /// </summary>
        public static string RequiredEmail {
            get {
                return ResourceManager.GetString("RequiredEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} must be at least {2} characters long..
        /// </summary>
        public static string RequiredLength {
            get {
                return ResourceManager.GetString("RequiredLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your password..
        /// </summary>
        public static string RequiredPassword {
            get {
                return ResourceManager.GetString("RequiredPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must provide the mobile phone number..
        /// </summary>
        public static string RequiredPhone {
            get {
                return ResourceManager.GetString("RequiredPhone", resourceCulture);
            }
        }
    }
}
