//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActionList
    {
        public ActionList()
        {
            this.Histories = new HashSet<History>();
            this.Emails = new HashSet<Email>();
        }
    
        public short Id { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<History> Histories { get; set; }
        public virtual ICollection<Email> Emails { get; set; }
    }
}
