//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Category
    {
        public Category()
        {
            this.URLs = new HashSet<URL>();
            this.Campaigns = new HashSet<Campaign>();
        }
    
        public decimal CategoryId { get; set; }
        public string Name { get; set; }
        public bool Status { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public decimal Budget { get; set; }
    
        public virtual ICollection<URL> URLs { get; set; }
        public virtual ICollection<Campaign> Campaigns { get; set; }
    }
}
