//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class City
    {
        public City()
        {
            this.URLs = new HashSet<URL>();
        }
    
        public decimal CityId { get; set; }
        public string Name { get; set; }
        public decimal CountryId { get; set; }
    
        public virtual Country Country { get; set; }
        public virtual ICollection<URL> URLs { get; set; }
    }
}
