//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Country
    {
        public Country()
        {
            this.Cities = new HashSet<City>();
        }
    
        public decimal CountryId { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public string TelephoneCode { get; set; }
    
        public virtual ICollection<City> Cities { get; set; }
    }
}
