//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Device
    {
        public Device()
        {
            this.NegativeMarchs = new HashSet<NegativeMarch>();
        }
    
        public decimal DeviceId { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<NegativeMarch> NegativeMarchs { get; set; }
    }
}
