//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class History
    {
        public decimal Id { get; set; }
        public short ActionId { get; set; }
        public System.DateTime NotedDate { get; set; }
        public string Description { get; set; }
        public string CreatedUser { get; set; }
        public string Object { get; set; }
    
        public virtual ActionList ActionList { get; set; }
        public virtual User User { get; set; }
    }
}
