//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Keyword
    {
        public Keyword()
        {
            this.NegativeMarchs = new HashSet<NegativeMarch>();
        }
    
        public decimal KeywordId { get; set; }
        public string Keyword1 { get; set; }
        public bool Status { get; set; }
        public short Marching { get; set; }
        public decimal Bid { get; set; }
        public decimal Budget { get; set; }
        public decimal URLId { get; set; }
    
        public virtual Keyword Keywords1 { get; set; }
        public virtual Keyword Keyword2 { get; set; }
        public virtual URL URL { get; set; }
        public virtual ICollection<NegativeMarch> NegativeMarchs { get; set; }
    }
}
