//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Link
    {
        public decimal Id { get; set; }
        public string URL { get; set; }
        public string Title { get; set; }
        public string ShortDescription { get; set; }
        public string Picture { get; set; }
        public string UserId { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<double> Price { get; set; }
        public decimal Reviews { get; set; }
        public decimal Rating { get; set; }
    
        public virtual User User { get; set; }
    }
}
