//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class NegativeMarch
    {
        public decimal KeywordId { get; set; }
        public decimal DeviceId { get; set; }
        public bool Negative { get; set; }
    
        public virtual Device Device { get; set; }
        public virtual Keyword Keyword { get; set; }
    }
}
