//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PriceURL
    {
        public decimal URLId { get; set; }
        public decimal CurrencyId { get; set; }
        public decimal Price { get; set; }
    
        public virtual Currency Currency { get; set; }
    }
}
