//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Task
    {
        public Task()
        {
            this.TransactionHistories = new HashSet<TransactionHistory>();
        }
    
        public decimal TaskId { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<TransactionHistory> TransactionHistories { get; set; }
    }
}
