//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransactionHistory
    {
        public decimal HistoryId { get; set; }
        public decimal TaskId { get; set; }
        public string UserId { get; set; }
        public System.DateTime Time { get; set; }
    
        public virtual Task Task { get; set; }
        public virtual User User { get; set; }
    }
}
