//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class URL
    {
        public URL()
        {
            this.DeviceTypeURLs = new HashSet<DeviceTypeURL>();
            this.Keywords = new HashSet<Keyword>();
        }
    
        public decimal Id { get; set; }
        public string URL1 { get; set; }
        public decimal Budget { get; set; }
        public bool Status { get; set; }
        public decimal CategoryId { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<decimal> DisplayCurrencyId { get; set; }
        public Nullable<decimal> DisplayLocationId { get; set; }
        public Nullable<decimal> DisplayTimeId { get; set; }
        public Nullable<int> DisplayTimes { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual City City { get; set; }
        public virtual Currency Currency { get; set; }
        public virtual ICollection<DeviceTypeURL> DeviceTypeURLs { get; set; }
        public virtual TimeFrame TimeFrame { get; set; }
        public virtual ICollection<Keyword> Keywords { get; set; }
    }
}
