//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Campaigns = new HashSet<Campaign>();
            this.TransactionHistories = new HashSet<TransactionHistory>();
            this.Links = new HashSet<Link>();
        }
    
        public string Phone { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public string PasswordSalt { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public bool IsActive { get; set; }
        public Nullable<System.DateTime> InActiveFrom { get; set; }
        public Nullable<System.DateTime> InActiveTo { get; set; }
        public string IP { get; set; }
        public short StatusId { get; set; }
        public string ActiveCode { get; set; }
        public string RegetPasswordCode { get; set; }
        public int Points { get; set; }
        public string Session { get; set; }
        public string CountryCode { get; set; }
    
        public virtual ICollection<Campaign> Campaigns { get; set; }
        public virtual Status Status { get; set; }
        public virtual ICollection<TransactionHistory> TransactionHistories { get; set; }
        public virtual ICollection<Link> Links { get; set; }
    }
}
